Controllers/UploadMusicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MoreMusic.DataLayer;
using MoreMusic.Services;

namespace MoreMusic.Controllers
{
    [Authorize]
    public class UploadMusicController : Controller
    {
        private readonly ILogger<MusicController> _logger;
        private readonly MusicDbContext _dbContext;
        private readonly IConfiguration _configuration;


        public UploadMusicController(ILogger<MusicController> logger, MusicDbContext dbContext, IConfiguration configuration)
        {
            _logger = logger;
            _dbContext = dbContext;
            _configuration = configuration;
        }

        public IActionResult UploadMusicPage()
        {
            return View("UploadMusicPage");
        }

        // POST: /UploadMusic
        [HttpPost]
        public ActionResult Index(string youtubeUrl)
        {
            UploadMusicService uploadMusic = new UploadMusicService(_dbContext, _configuration);

            var importDetails = uploadMusic.Uploader(youtubeUrl).Result;
            uploadMusic.InsertAudioFileToDb(importDetails);

            ViewBag.Message = "URL received: " + youtubeUrl;
            return View("UploadMusicPage");
        }

    }
}

Views/UploadMusic/UploadMusicPage.cshtml
@{
    ViewBag.Title = "Upload Music Page";
}

<h2>Upload Music Page</h2>

@using (Html.BeginForm("Index", "UploadMusic", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("YouTube URL:")
        @Html.TextBox("youtubeUrl", null, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-success mt-3">
        @ViewBag.Message
    </div>
}